GITHUB_URL = 'https://github.com/Nerdman4U/unite2024'
VESL_URL = 'https://www.vesl.fi'
VESL_NAME = 'The Green Association for the Protection of Life'
TEP_URL = "http://tekniikkaelamaapalvelemaan.fi"
TEP_NAME = "Technology for Life"
UNITE_ROOT_URL = 'http://unitethearmies.org'
UNITE_TITLE = "Save the Planet - Unite the Armies!"
UNITE_LOGO = "logo.png"
UNITE_LOGO_DARK = "logo-dark.png"
UNITE_DOMAIN = "unitethearmies.org"
UNITE_SMTP_DOMAIN = 'unite-the-armies.org'
UNITE_THE_ARMIES_EMAIL = "info@jonitoyryla.eu"
UNITE_THE_ARMIES_TEST_EMAIL = "info@jonitoyryla.eu"
UNITE_DESCRIPTION = "Radical actions are urgently needed to save our planet. STOP THE DISASTER – NOW!"
UNITE_SHARE_MESSAGE = "Sign an appeal for the UN to ask armies to participate on the preventive work against climate catastrophe. http://unitethearmies.org/"
UNITE_FACEBOOK_URL = "https://www.facebook.com/unitethearmiesnow"
UNITE_YOUTUBE_URL = "https://www.youtube.com/channel/UCbBytuGB3cDGyJ2RCSWpovw"
UNITE_GOOGLEPLUS_URL = "https://plus.google.com/u/0/b/110514912421465474435/110514912421465474435/about/p/pub"
UNITE_DOWNLOAD_URL = "http://unite-the-armies.org/en/download"
CAMPAIGN_ASSISTANT_EMAIL = "info@jonitoyryla.eu"

